version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: unless-stopped    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: admin_panel
    restart: unless-stopped